config/routes.rb
Rails.application.routes.draw do
  get 'general/index'

  devise_for :users
  root 'improgroups#index'
  resources :improgroups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/improgroup.rb
class Improgroup < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def index
  end
end

app/controllers/improgroups_controller.rb
class ImprogroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_improgroup, only: [:show, :edit, :update, :destroy]

  # GET /improgroups
  # GET /improgroups.json
  def index
    @improgroups = Improgroup.all
  end

  # GET /improgroups/1
  # GET /improgroups/1.json
  def show
  end

  # GET /improgroups/new
  def new
    @improgroup = Improgroup.new
  end

  # GET /improgroups/1/edit
  def edit
  end

  # POST /improgroups
  # POST /improgroups.json
  def create
    @improgroup = Improgroup.new(improgroup_params)

    respond_to do |format|
      if @improgroup.save
        format.html { redirect_to @improgroup, notice: 'Improgroup was successfully created.' }
        format.json { render :show, status: :created, location: @improgroup }
      else
        format.html { render :new }
        format.json { render json: @improgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /improgroups/1
  # PATCH/PUT /improgroups/1.json
  def update
    respond_to do |format|
      if @improgroup.update(improgroup_params)
        format.html { redirect_to @improgroup, notice: 'Improgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @improgroup }
      else
        format.html { render :edit }
        format.json { render json: @improgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /improgroups/1
  # DELETE /improgroups/1.json
  def destroy
    @improgroup.destroy
    respond_to do |format|
      format.html { redirect_to improgroups_url, notice: 'Improgroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_improgroup
      @improgroup = Improgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def improgroup_params
      params.require(:improgroup).permit(:name_improgroups, :creation_year, :actors_improgroups, :image_improgroups)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/improgroups_helper.rb
module ImprogroupsHelper
end

app/views/general/index.html.erb
<h1>General#index</h1>
<p>Find me in app/views/general/index.html.erb</p>

app/views/improgroups/_form.html.erb
<%= form_for(improgroup) do |f| %>
  <% if improgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(improgroup.errors.count, "error") %> prohibited this improgroup from being saved:</h2>

      <ul>
      <% improgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_improgroups %>
    <%= f.text_field :name_improgroups %>
  </div>

  <div class="field">
    <%= f.label :creation_year %>
    <%= f.text_field :creation_year %>
  </div>

  <div class="field">
    <%= f.label :actors_improgroups %>
    <%= f.text_field :actors_improgroups %>
  </div>

  <div class="field">
    <%= f.label :image_improgroups %>
    <%= f.text_field :image_improgroups %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/improgroups/edit.html.erb
<h1>Editing Improgroup</h1>

<%= render 'form', improgroup: @improgroup %>

<%= link_to 'Show', @improgroup %> |
<%= link_to 'Back', improgroups_path %>

app/views/improgroups/index.html.erb
<header class="masthead text-center text-white d-flex">
<div class="container my-auto">
 <div class="row">
   <div class="col-lg-10 mx-auto">
     <h1 class="text-uppercase">
       <strong>RED NACIONA DE IMPRO </strong>
     </h1>

   </div>
   <div class="col-lg-8 mx-auto">
     <p class="text-faded mb-5"></p>
     <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
   </div>
 </div>
</div>
</header>


<p id="notice"><%= notice %></p>

<div class="container">
<h1>Improgroups</h1>
</div>
<div class="container">
<table class="table">
  <div class="container col-md-12">
    <thead>
      <tr>
        <th>Name improgroups</th>
        <th>Creation year</th>
        <th>Actors improgroups</th>
        <th>Image improgroups</th>
        <th colspan="10"></th>
      </tr>
    </thead>
  </div>
</div>

  <tbody>
    <% @improgroups.each do |improgroup| %>
      <tr>
        <td><%= improgroup.name_improgroups %></td>
        <td><%= improgroup.creation_year %></td>
        <td><%= improgroup.actors_improgroups %></td>
        <td><%= improgroup.image_improgroups %></td>
        <td><%= link_to 'Show', improgroup %></td>
        <td><%= link_to 'Edit', edit_improgroup_path(improgroup) %></td>
        <td><%= link_to 'Destroy', improgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-primary">
  <%= link_to 'New Improgroup', new_improgroup_path %>
</button>

app/views/improgroups/new.html.erb
<div class="container-fluid">
  <h1>New Improgroup</h1>
</div>
  <div class="container">
    <h2><%= render 'form', improgroup: @improgroup %></h2>
  </div>

<button type="button" name="button"></button>
<%= link_to 'Back', improgroups_path %>

app/views/improgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name improgroups:</strong>
  <%= @improgroup.name_improgroups %>
</p>

<p>
  <strong>Creation year:</strong>
  <%= @improgroup.creation_year %>
</p>

<p>
  <strong>Actors improgroups:</strong>
  <%= @improgroup.actors_improgroups %>
</p>

<p>
  <strong>Image improgroups:</strong>
  <%= @improgroup.image_improgroups %>
</p>

<%= link_to 'Edit', edit_improgroup_path(@improgroup) %> |
<%= link_to 'Back', improgroups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<html>
  <head>
    <title>Reddeimpro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <h1 class="container ">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </h1>
    <!-- Navigation -->
    <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#services">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- Navigation bar end  -->



    <%= yield %>
  </body>
</html>